# Generated by Django 4.1 on 2023-06-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmarksvoice',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='downvoice',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='upvoice',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterField(
            model_name='user',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', through='blog_api.BookmarksVoice', to='blog_api.publication'),
        ),
        migrations.AlterField(
            model_name='user',
            name='voices_down',
            field=models.ManyToManyField(blank=True, related_name='voices_down', through='blog_api.DownVoice', to='blog_api.publication'),
        ),
        migrations.AlterField(
            model_name='user',
            name='voices_up',
            field=models.ManyToManyField(blank=True, related_name='voices_up', through='blog_api.UpVoice', to='blog_api.publication'),
        ),
    ]
